<?php

/**
 * @file
 * Contains cypress_smoketest.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function cypress_smoketest_help(string $route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the cypress_smoketest module.
    case 'help.page.cypress_smoketest':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Helper module to perform Cypress smoketest on Drupal') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_page_attachments_alter().
 */
function cypress_smoketest_page_attachments_alter(array &$attachments) {
  $current_route = \Drupal::routeMatch();
  $route_name = $current_route->getRouteName();

  if ($route_name == 'devel.configs_list') {
    // phpcs:ignore DrupalPractice.CodeAnalysis.VariableAnalysis.UnusedVariable
    $watchdog_error = $attachments['watchdog-error'];
    $attachments['#attached']['html_head'][] = [
      [
        '#type' => 'html_tag',
        '#tag' => 'script',
        '#value' => "throw new Error('First js error');",
      ],
      'javascript-error-1',
    ];
    $attachments['#attached']['html_head'][] = [
      [
        '#type' => 'html_tag',
        '#tag' => 'script',
        '#value' => "throw new Error('Second js error');",
      ],
      'javascript-error-2',
    ];
  }
}
