<?php

/**
 * @file
 * Contains cypress_smoketest.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function cypress_smoketest_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the cypress_smoketest module.
    case 'help.page.cypress_smoketest':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Helper module to perform Cypress smoketest on Drupal') . '</p>';
      return $output;

    default:
  }
}

function cypress_smoketest_page_attachments(array &$attachments) {
  $current_route = \Drupal::routeMatch();
  $route_name = $current_route->getRouteName();

  if($route_name == 'view.frontpage.page_1') {
    $attachments['#attached']['html_head'][] = [
      // The data.
      [
        '#type' => 'html_tag',
        '#tag' => 'script',
        '#value' => "throw new Error('Javascript error simulation!');",

      ],
      'javascript-error',
    ];
  }
}
