version: '3'
services:

  web:
    build: lib/docker/apache
    environment:
      APPLITOOLS_API_KEY:
      APACHE_DOCUMENT_ROOT: ${PWD}/web
      PHP_EXTENSION_GD: 1
      GIT_USER_NAME:
      GIT_USER_EMAIL:
    working_dir: ${PWD}
    volumes:
      - ${PWD}:${PWD}
      - ~/.ssh:/home/docker/.ssh
    ports:
      - 81:80
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./lib/mysql:/docker-entrypoint-initdb.d

  # To start with x11 first allow connections by executing: xhost +
  # Then execute: docker-compose run --rm --entrypoint="cypress open --project ${PWD}" cypress
  # To end with x11 make sure you put access control back on by executing: xhost -
  # To just run the tests execute: docker-compose run --rm --entrypoint="cypress run" cypress
  cypress:
    image: cypress/included:7.3.0
    depends_on:
      - web
    environment:
      APPLITOOLS_API_KEY:
      CYPRESS_baseUrl: http://web
      DISPLAY:
    working_dir: ${PWD}
    volumes:
      - ${PWD}:${PWD}
      - /tmp/.X11-unix:/tmp/.X11-unix
