version: '3.4'
services:
  web:
    build: lib/docker/apache
    environment:
      APPLITOOLS_API_KEY:
      CYPRESS_CACHE_FOLDER: ${PWD}/vendor/bin
      CYPRESS_baseUrl: http://web
      APACHE_DOCUMENT_ROOT: ${PWD}/web
      PHP_EXTENSION_GD: 1
      PHP_EXTENSION_XDEBUG: 1
      GIT_USER_NAME:
      GIT_USER_EMAIL:
      DISPLAY:
    working_dir: ${PWD}
    volumes:
      - ${PWD}:${PWD}
      - ~/.ssh:/home/docker/.ssh
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - 81:80
    depends_on:
      - mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 5s
      timeout: 60s
      retries: 5
      start_period: 30s

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./lib/mysql:/docker-entrypoint-initdb.d
    healthcheck:
      test: 'mysql --user=root --password="" --execute="SHOW DATABASES;"'
      interval: 5s
      timeout: 60s
      retries: 5
      start_period: 30s
