name: Push on master

on:
  push:
    branches:
      - master
      - 1.0.x

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache build
        id: cache-build
        uses: actions/cache@v2
        with:
          path: |
            vendor/
            web/
            node_modules/
          key: build-${{ hashFiles('composer.lock', 'package-lock.json') }}

      - name: Setup environment
        env:
          APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
        run: |
          docker-compose up -d web mysql
          while [ $(docker-compose ps | grep -c healthy) -lt 2 ]; do sleep 5; echo "Waiting for services"; done
          docker-compose ps

      - name: Run Grumphp
        run: |
          docker-compose exec -T web grumphp run

      - name: Run Cypress
        run: |
          docker-compose exec -T web cypress install
          docker-compose exec -T web cypress run

      - name: Upload test results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress
          path: |
            cypress/results
            cypress/screenshots
            cypress/videos

